// cdb_parser.h
// CDB parser for SDCC compiler output files.
//
// Copyright 2025 Tomaz Stih. All rights reserved.
// MIT License.
#pragma once

#include <string>
#include <vector>
#include <optional>
#include <string_view>
#include <unordered_map>

#include <sdcc/cdbg_info.h>

namespace sdcc {

// Parses C debug information (.cdb) files generated by the SDCC compiler.
// Extracts module, function, symbol, type, and line-address mappings.
// Also captures assembly line records (L:A$) into cdbg_info_module::asm_lines,
// creating stub modules for pure-assembly files (e.g. crt0) that have no M: record.
class cdb_parser {
public:
    // Parse file at path.  Returns the module list on success, nullopt on error.
    std::optional<std::vector<cdbg_info_module>> parse(const std::string &path);

    // Access the last successfully parsed data without re-parsing.
    const std::vector<cdbg_info_module> &data() const { return data_; }

private:
    void parse_line(std::string_view line);
    void parse_module(std::string_view content);
    void parse_function(std::string_view content);
    void parse_symbol(std::string_view content);
    void parse_type(std::string_view content);
    void parse_line_info(std::string_view content);
    void parse_func_marker(std::string_view content, bool is_end);
    void merge_asm_lines(); // run once after all records are parsed

    std::vector<cdbg_info_module> data_;
    std::string current_module_;
    cdbg_info_module *current_module_ptr_ = nullptr;
    // Accumulates A$module$line:addr records independently of M: declarations
    // so pure-assembly modules (crt0, etc.) are handled correctly.
    std::unordered_map<std::string,
                       std::unordered_map<int, uint16_t>> asm_lines_;
};

} // namespace sdcc
